### ISSUE TITLE
CIPP still causing redirects when trying to translate

### ISSUE THREAD

**Issue by Krista-Nuams** [ABREPR/cipp#76]
I tried to translate http://live-cipp.nuamsdev.com/es/node/674/edit because the English still contained Spanish.  When I clicked Translate and hit edit for the English, it brought me here http://live-cipp.nuamsdev.com/en/node/674/edit/en. I made the change and clicked finish.  
Unexpected behavior:
1) This automatically cause a redirect direct loop I have since deleted.
2) the English then automatically 
![why did my change to the english appear in the spanish](https://f.cloud.github.com/assets/4095552/2020892/bc0ab6d8-8837-11e3-9ff8-a4060b25da10.png)
![translate dataset with translate button2](https://f.cloud.github.com/assets/4095552/2020893/bc0c1136-8837-11e3-8a6d-1fc3b7fc6996.png)
![translate dataset with translate button](https://f.cloud.github.com/assets/4095552/2020894/bc0e9780-8837-11e3-8688-9669823578c9.png)

appeared in the Spanish. I am attempting to correct that now.

**Comment by Krista-Nuams** [comment]
When I tried to correct # 2 and delete the English that wasn't supposed to be there I got this rude message:
Dataset Crimen Región de Ponce has been updated.
Oops, looks like this request tried to create an infinite loop. We do not allow such things here. We are a professional website!
![another redirect loop when trying to correct spanish](https://f.cloud.github.com/assets/4095552/2020924/21603dbe-8838-11e3-955f-1d2433ccb2ad.png)

**Comment by Krista-Nuams** [comment]
Now I deleted all redirects. And clicked save and more redirects appeared.
![more redirects after deleting redirects](https://f.cloud.github.com/assets/4095552/2020996/db5d8280-8838-11e3-9444-ba5842ed4e5c.png)

**Comment by Krista-Nuams** [comment]
What is the status of this?

**Comment by acouch** [comment]
We removed "Automatically create redirects when URL aliases are changed." which I believe should fix this.

**Comment by Krista-Nuams** [comment]
I am still getting the redirect when I click Finish (save) on http://live-cipp.nuamsdev.com/es/node/674/edit
![still redirects2](https://f.cloud.github.com/assets/4095552/2072770/0c05d0d8-8d46-11e3-8f0c-0d1c375c26e6.png)
![still redirects](https://f.cloud.github.com/assets/4095552/2072772/0e41bec0-8d46-11e3-9c01-8768d8b70cea.png)

**Comment by Krista-Nuams** [comment]
From the client:
I have been having a recurring problem with infinite loops. You see, I have deleted the redirects on the pages that present infinite loops as instructed on basecamp, and immediately after saving the changes (deletion of redirects) they automatically reappear on the page. How can I permanently delete them to eliminate the infinite loops?

**Comment by Krista-Nuams** [comment]
Dan fixed this. Just need th e commit info in order to close.
